In [2]:
import numpy as np

In [3]:
a1 = np.array([5, 9, 1])
print(a1)
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(a1.shape)
print(a2.shape)

[5 9 1]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [3]:
print(a1 + 10)
print(a1 - 1)
print(1 / a1)
print(a1 * a1)
print(a1 ** 3)

[15 19 11]
[4 8 0]
[0.2        0.11111111 1.        ]
[25 81  1]
[125 729   1]


In [4]:
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([1, 2])
print(a + b)

[[1 3]
 [3 5]
 [5 7]]


In [5]:
print(a.shape)
print(b.shape)

(3, 2)
(2,)


In [6]:
a1 = np.array([[0], [1], [2]])
b1 = np.array([1, 2, 3])
print(a1 + b1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [7]:
a2 = np.array([[0, 1], [2, 3], [4, 5]])
b2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2 + b2)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [8]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b3 = np.array([[1], [4]])
print(a3 + b3)

[[[ 2  3  4]
  [ 8  9 10]]

 [[ 8  9 10]
  [14 15 16]]]
